pipeline:
    name: Example
    identifier: Example
    projectIdentifier: GitExp_Doc_Example
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: helloworld
              identifier: helloworld
              type: CI
              spec:
                  cloneCodebase: false
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: example
                                identifier: example
                                spec:
                                    connectorRef: <+input>
                                    image: <+input>
                                    command: echo "hello world"
                                    privileged: false
                                failureStrategies: []
                  serviceDependencies: []
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: <+input>
                          namespace: default
